// src/utils/endpoints.js
// Centralized backend endpoint registry for Joyory Frontend

export const endpoints = {
  auth: {
    login: "/api/user/login",
    signup: "/api/user/signup",
    logout: "/api/user/logout",
    deleteAccount: "/api/user/delete-account",
    otpSend: "/api/user/otp/send",
    otpVerify: "/api/user/otp/verify",
    otpCompleteProfile: "/api/user/otp/complete-profile",
    forgotPassword: "/api/security/forgot-password",
    resetPassword: "/api/security/reset-password",
    securitySendOtp: "/api/security/send-otp",
    securityVerifyOtp: "/api/security/verify-otp",
  },
  user: {
    profile: "/api/user/profile",
    avatar: "/api/user/profile/avatar",
    address: "/api/user/profile/address",
    addressById: (id) => `/api/user/profile/address/${id}`,
    sendOtp: "/api/user/profile/send-otp",
    verifyOtp: "/api/user/profile/verify-otp",
  },
  wallet: {
    base: "/api/user/wallet",
    createOrder: "/api/user/wallet/create-order",
    verifyPayment: "/api/user/wallet/verify-payment",
    redeem: "/api/user/wallet/redeem",
    refund: "/api/user/wallet/refund",
    addReward: "/api/user/wallet/add-reward",
  },
  products: {
    all: "/api/user/products/all",
    details: (idOrSlug) => `/api/user/products/${idOrSlug}`,
    topSellers: "/api/user/products/top-sellers",
    topCategories: "/api/user/products/top-categories",
    filters: "/api/user/products/filters",
    skinTypes: "/api/user/products/skin-types",
    categoryProducts: (slug) => `/api/user/products/category/${slug}/products`,
  },
  categories: {
    tree: "/api/user/categories/tree",
    landing: (slug) => `/api/user/categories/category/${slug}/landing`,
    products: (slug) => `/api/user/categories/category/${slug}/products`,
  },
  brands: {
    list: "/api/user/brands",
    bySlug: (slug) => `/api/user/brands/${slug}`,
    brandCategoryProducts: (brandSlug, categorySlug) => `/api/user/brands/${brandSlug}/${categorySlug}`,
  },
  cart: {
    base: "/api/user/cart",
    add: "/api/user/cart/add",
    update: "/api/user/cart/update",
    remove: (productId) => `/api/user/cart/remove/${productId}`,
    summary: "/api/user/cart/summary",
    applyCoupon: "/api/user/cart/apply-coupon",
    removeCoupon: "/api/user/cart/remove-coupon",
    orders: "/api/user/cart/orders",
    orderInitiate: "/api/user/cart/order/initiate",
    tracking: (orderId) => `/api/user/cart/tracking/${orderId}`,
    cancelOrder: (orderId) => `/api/user/cart/cancel/${orderId}`,
    shipment: (shipmentId) => `/api/user/cart/shipment/${shipmentId}`,
    cancelShipment: (shipmentId) => `/api/user/cart/shipment/cancel/${shipmentId}`,
    invoice: (invoiceId) => `/api/user/cart/invoice/${invoiceId}`,
    discount: (discountId) => `/api/user/cart/discount/${discountId}`,
    moveToWishlist: (productId) => `/api/user/cart/${productId}/move-to-wishlist`,
  },
  wishlist: {
    base: "/api/user/wishlist",
    item: (productId) => `/api/user/wishlist/${productId}`,
    moveToCart: (productId) => `/api/user/wishlist/${productId}/move-to-cart`,
  },
  orders: {
    byId: (orderId) => `/api/user/orders/${orderId}`,
    paymentSuccess: (orderId) => `/api/payment/success/${orderId}`,
  },
  returns: {
    request: (shipmentId) => `/api/returns/request/${shipmentId}`,
    my: "/api/returns/my",
    details: (shipmentId, returnId) => `/api/returns/details/${shipmentId}/${returnId}`,
    cancel: (shipmentId, returnId) => `/api/returns/cancel/${shipmentId}/${returnId}`,
  },
  payment: {
    methods: "/api/payment/methods",
    setPaymentMethod: "/api/payment/set-payment-method",
    cod: "/api/payment/cod",
    codConfirm: "/api/payment/cod/confirm",
    razorpayOrder: "/api/payment/razorpay/order",
    razorpayVerify: "/api/payment/razorpay/verify",
    wallet: "/api/payment/wallet",
    giftcard: "/api/payment/giftcard",
    refundMethods: "/api/payment/refund-methods",
    refundMethod: "/api/payment/refund-method",
    cancel: "/api/payment/cancel",
  },
  reviews: {
    add: "/api/reviews/add",
    byProduct: (productId) => `/api/reviews/product/${productId}`,
    topByProduct: (productId) => `/api/reviews/product/${productId}/top`,
    voteHelpful: (reviewId) => `/api/reviews/${reviewId}/vote-helpful`,
    react: (reviewId) => `/api/reviews/${reviewId}/react`,
    report: (reviewId) => `/api/reviews/${reviewId}/report`,
  },
  ingredients: {
    list: "/api/ingredients",
    byName: (name) => `/api/ingredients/${encodeURIComponent(name)}`,
    compatibility: "/api/ingredients/compatibility",
    productsByName: (name) => `/api/ingredients/${encodeURIComponent(name)}/products`,
    scanProduct: (id) => `/api/ingredients/scan/product/${id}`,
    userAllergens: "/api/ingredients/user/allergens",
    productCompatibility: "/api/ingredients/product-compatibility",
    productSafety: (productId) => `/api/ingredients/product-safety/${productId}`,
    scanText: "/api/ingredients/scan-text",
  },
  beautyConcierge: {
    chat: "/api/user/beauty-concierge/chat",
    history: "/api/user/beauty-concierge/history",
    quickRecs: "/api/user/beauty-concierge/quick-recs",
  },
  skinDiagnosis: {
    analyze: "/api/user/skin-diagnosis/analyze",
    exportRoutine: "/api/user/skin-diagnosis/export-routine",
    history: "/api/user/skin-diagnosis/history",
    byId: (id) => `/api/user/skin-diagnosis/${id}`,
  },
  routines: {
    my: "/api/user/routines/my",
    create: "/api/user/routines/create",
    byId: (routineId) => `/api/user/routines/${routineId}`,
    publicByToken: (shareToken) => `/api/user/routines/public/${shareToken}`,
    share: (routineId) => `/api/user/routines/${routineId}/share`,
    activeReminders: "/api/user/routines/reminders/active",
    templates: "/api/user/routines/templates",
    aiBuild: "/api/user/routines/ai-build",
    checkConflicts: "/api/user/routines/check-conflicts",
    validateOrder: "/api/user/routines/validate-order",
    audit: (routineId) => `/api/user/routines/${routineId}/audit`,
    coach: (routineId) => `/api/user/routines/${routineId}/coach`,
    logs: (routineId) => `/api/user/routines/${routineId}/logs`,
    log: (routineId) => `/api/user/routines/${routineId}/log`,
    calendar: (routineId) => `/api/user/routines/${routineId}/calendar`,
    uploadProgressPhoto: "/api/user/routines/upload-progress-photo",
    alternatives: (productId) => `/api/user/routines/products/${productId}/alternatives`,
    clone: (shareToken) => `/api/user/routines/clone/${shareToken}`,
    suggest: "/api/user/routines/suggest",
    addToCart: (routineId) => `/api/user/routines/${routineId}/add-to-cart`,
  },
  vto: {
    enabled: "/api/vto/enabled",
    workflow: "/api/vto/workflow",
  },
  shadeFinder: {
    tones: "/api/user/shadefinder/tones",
    undertones: "/api/user/shadefinder/undertones",
    families: "/api/user/shadefinder/families",
    formulations: "/api/shadefinder/formulations", // NOTE: NOT under /api/user/
    recommendations: "/api/user/shadefinder/recommendations",
  },
  giftCards: {
    createOrder: "/api/user/giftcards/create-order",
    verifyPayment: "/api/user/giftcards/verify-payment",
    redeem: "/api/user/giftcards/redeem",
    balance: (code, pin) => `/api/user/giftcards/balance/${code}/${pin}`,
    list: "/api/user/giftcards/list",
    details: (id) => `/api/user/giftcards/details/${id}`,
    templates: "/api/user/giftcards/templates",
  },
  promotions: {
    active: "/api/user/promotions/active",
    offersPage: "/api/user/promotions/offers-page",
    bySlug: (idOrSlug) => `/api/user/promotions/${idOrSlug}/products`,
  },
  discounts: {
    eligible: "/api/user/discounts/eligible",
    validate: "/api/user/discounts/validate",
  },
  videos: {
    list: "/api/user/videos",
    bySlug: (slug) => `/api/user/videos/${slug}`,
    view: (id) => `/api/user/videos/${id}/view`,
  },
  forYou: {
    intro: "/api/user/for-you/intro",
    makeupGuide: "/api/user/for-you/makeup-guide",
    skincareQuestions: "/api/user/for-you/skincare/questions",
    skincareSubmit: "/api/user/for-you/skincare/submit",
    skincareProfile: "/api/user/for-you/skincare/profile",
    recommendations: "/api/user/for-you/recommendations",
  },
  featureBanners: {
    list: "/api/user/feature-banners",
  },
  referral: {
    code: "/api/referral/code",
    history: "/api/referral/history",
  },
  affiliate: {
    signup: "/api/affiliate/signup",
    login: "/api/affiliate/login",
  },
  recommendations: {
    base: "/api/user/recommendations",
    cart: "/api/user/recommendations/cart",
    personalSummary: "/api/user/recommendations/personal-summary",
    personalized: "/api/user/recommendations/personalized",
  },
  blogs: {
    list: "/api/blogs",
    landing: "/api/blogs/landing",
    byIdOrSlug: (idOrSlug) => `/api/blogs/${idOrSlug}`,
    bySlug: (slug) => `/api/blogs/slug/${slug}`,
  },
  seo: {
    base: "/api/seo",
  },
  media: {
    base: "/api/media",
  },
  tracking: {
    duration: "/api/tracking/duration",
    pageview: "/api/tracking/pageview",
    consent: "/api/tracking/consent",
  },
};

export default endpoints;
